version: "3.8"
services:
  minecraft-overviewer:
    image: mc-renderer:latest-dev
    volumes:
      - ./world:/world:ro
      - ./render:/render
    tmpfs:
      - /cache:size=4G,uid=1000
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '12.00'
          memory: 8G
  proxy:
    image: caddy:2.1.1-alpine
    depends_on:
      - minecraft-overviewer
    volumes:
      - ./render:/render:ro
    entrypoint: ["caddy", "file-server", "--root", "/render", "--listen", ":1234"]
    ports:
      - 1234:1234
    deploy:
      mode: replicated
      replicas: 1
